### ISSUE TITLE
Second-to-last cell throws an error

### ISSUE THREAD

**Issue by BahnDaten** [GeeveGeorge/Stable-Craiyon#2]
Tried the colab notebook; the Craiyon part works fine, but the Stable Diffusion one throws an error before I could see my prompt Diffusion-ized.
![image](https://user-images.githubusercontent.com/54518068/189248170-ce6cf075-4bcb-44ca-96cb-9786e6eafed4.png)

**Comment by GeeveGeorge** [comment]
@BahnDaten , the issue has been fixed.
You can check out the updated notebook! :)
