### ISSUE TITLE
'AutoencoderKLOutput' object has no attribute 'sample'

### ISSUE THREAD

**Issue by leolenz** [GeeveGeorge/Stable-Craiyon#3]
Here is the error:

AttributeError                            Traceback (most recent call last)

[<ipython-input-13-0c61338d0c7e>](https://localhost:8080/#) in <module>
      1 generator = torch.Generator(device=device).manual_seed(1024)
      2 with autocast("cuda"):
----> 3     images = pipe(prompt=prompt, init_image=init_image, strength=0.75, guidance_scale=7.5, generator=generator)["sample"]

1 frames

[<ipython-input-5-4fb8144e2978>](https://localhost:8080/#) in __call__(self, prompt, init_image, strength, num_inference_steps, guidance_scale, eta, generator, output_type)
     56 
     57         # encode the init image into latents and scale the latents
---> 58         init_latents = self.vae.encode(init_image.to(self.device)).sample()
     59         init_latents = 0.18215 * init_latents
     60 

AttributeError: 'AutoencoderKLOutput' object has no attribute 'sample'

------------------

I found a similar problem in a different notebook.
There they responded:

> We need to update this notebook for diffusers==0.3.0!
For now could you replace:
latents = vae.encode(batch["pixel_values"]).sample().detach()
with
latents = vae.encode(batch["pixel_values"]).latent_dist.sample().detach()

but I couldn't find out what to change in this Stable Craiyon notebook

**Comment by GeeveGeorge** [comment]
@leolenz , the issue has been fixed.
You can check out the updated notebook! :)
